Implement API key management
bramhaag/OwOUploader pull request #40
Opened 2021-05-12 18:53 UTC by NahuLD

Resolves #4, resolves #6.

This branch will only add the basic feature of storage and validation for the API key, proper integration will have to be done separately.

2021-07-16 00:22 UTC, NahuLD commented
Everything seems to be working, but I had to wait 3 months for the PR mature

2021-07-16 01:00 UTC, bramhaag requested changes
cya next year

2021-07-23 21:19 UTC, bramhaag commented on app/src/main/java/me/bramhaag/owouploader/activity/LoginActivity.java
> +                        finish();
Maybe we should make a Toast message here explaining to the user that something unexpected happened, unless you're convinced that this should never happen

2021-07-23 21:19 UTC, bramhaag commented on app/src/main/java/me/bramhaag/owouploader/activity/MainActivity.java
> +    public OwOAPI getApi() {
why? is this used ever?

2021-07-23 21:58 UTC, NahuLD commented on app/src/main/java/me/bramhaag/owouploader/activity/LoginActivity.java
> +                        finish();
Imagine actually handling errors and not just closing the app :sunglasses:

2021-07-23 21:58 UTC, NahuLD commented on app/src/main/java/me/bramhaag/owouploader/activity/MainActivity.java
> +    public OwOAPI getApi() {
No, I thought it was needed to make DI work

2021-07-23 22:03 UTC, bramhaag commented on app/src/main/java/me/bramhaag/owouploader/activity/MainActivity.java
> +    public OwOAPI getApi() {
it's not, you can get rid of it

2021-07-23 22:06 UTC, bramhaag approved these changes

2021-07-23 22:07 UTC, merged